### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by flmel** [near/pagoda-relayer-rs#58]
Hey we had this on Discord 

```
So this relayer from pagoda looks to be a great base for building my own relayer from, 
but there's no license listed. Do you know what kind of license this github project is under? 
Thanks!
https://github.com/near/pagoda-relayer-rs
```

I would assume it's MIT 
@anthony-near

**Comment by anthony-near** [comment]
Hi @flmel I'm double checking but I think it's MIT. PR for license here: https://github.com/near/pagoda-relayer-rs/pull/59. When it's merged then the license will be official :)

**Comment by anthony-near** [comment]
Merged. MIT license
