### ISSUE TITLE
Some configs pointing to old NEAR Wallet

### ISSUE THREAD

**Issue by mikedotexe** [near/pagoda-relayer-rs#66]
Small one, but noticed that in the `configs` directory we probably need to point elsewhere, like to https://testnet.mynearwallet.com instead of 

```
wallet_url = "https://wallet.testnet.near.org"
```

**Comment by anthony-near** [comment]
wallet no longer used in relayer. removed in this branch: https://github.com/near/pagoda-relayer-rs/pull/65
