### ISSUE TITLE
Some configs pointing to old NEAR Explorer

### ISSUE THREAD

**Issue by mikedotexe** [near/pagoda-relayer-rs#67]
Also noticed this:

```
explorer_transaction_url = "https://explorer.testnet.near.org/transactions/"
```

But it's been deprecated and visiting it gives this:

<img width="781" alt="Screenshot 2024-03-08 at 1 48 50 PM" src="https://github.com/near/pagoda-relayer-rs/assets/1042667/a790cfe8-35b0-44cd-b7e2-342bbf3ba3bf">

Seems like we'll need to use a link to NEARBlocks instead (https://nearblocks.io)

**Comment by anthony-near** [comment]
explorer is no longer used by relayer. update to remove in this branch: https://github.com/near/pagoda-relayer-rs/pull/65
