### ISSUE TITLE
Remove dependency on near-fetch

### ISSUE THREAD

**Issue by r-near** [near/pagoda-relayer-rs#91]

**Comment by anthony-near** [comment]
This is only an issue bc of sub dependency conflicts when updating the `near-jsonrpc-client` crate to `0.9.0`. We'll be replacing the `KeyRotatingSigner` from `near-fetch` with a persistent state store for the keys to rotate through and a locking mechanism. Related issues: https://github.com/near/pagoda-relayer-rs/issues/87, https://github.com/near/pagoda-relayer-rs/issues/55

**Comment by r-near** [comment]
Yep - another option would be to update near-fetch to match our dependencies. I [found that to be easier](https://github.com/ChaoticTempest/fetch/pull/13). We rely so heavily on near-fetch's rpc_client, it would be a pain to rewrite all that.
